#include "Array Ex.h"
#include "D2 Structs.h"

#ifdef PTRS

enum
{
	DLLNO_D2CLIENT,
	DLLNO_D2COMMON,
	DLLNO_D2GFX,
	DLLNO_D2LANG,
	DLLNO_D2WIN,
	DLLNO_D2NET,
	DLLNO_D2GAME,
	DLLNO_D2LAUNCH,
	DLLNO_FOG,
	DLLNO_BNCLIENT,
	DLLNO_STORM,
	DLLNO_D2CMP,
	DLLNO_D2MULTI,
	DLLNO_D2MCPCLIENT
};

#define DLLOFFSET(A1, A2)		((DLLNO_##A1) | ((A2) << 8))
#define FUNCTION(D, N, T, A, O)	typedef T D##_##N##_t A; D##_##N##_t *D##_##N = (D##_##N##_t *)DLLOFFSET(D, O);
#define VARIABLE(D, N, T, O)	typedef T D##_##N##_t;    D##_##N##_t *p_##D##_##N = (D##_##N##_t *)DLLOFFSET(D, O);
#define ASSEMBLER(D, N, O)		DWORD D##_##N = DLLOFFSET(D, O);

#else

enum
{
	DLLNO_D2CLIENT,
	DLLNO_D2COMMON,
	DLLNO_D2GFX,
	DLLNO_D2LANG,
	DLLNO_D2WIN,
	DLLNO_D2NET,
	DLLNO_D2GAME,
	DLLNO_D2LAUNCH,
	DLLNO_FOG,
	DLLNO_BNCLIENT,
	DLLNO_STORM,
	DLLNO_D2CMP,
	DLLNO_D2MULTI,
	DLLNO_D2MCPCLIENT
};

#define DLLOFFSET(A1, A2)		((DLLNO_##A1) | ((A2) << 8))
#define FUNCTION(D, N, T, A, O)	typedef T D##_##N##_t A;	extern D##_##N##_t *D##_##N;
#define VARIABLE(D, N, T, O)	typedef T D##_##N##_t;		extern D##_##N##_t *p_##D##_##N;
#define ASSEMBLER(D, N, O)		extern DWORD D##_##N;

#define BNCLIENT_BASE		0x6FF20000
#define D2CLIENT_BASE		0x6FAB0000
#define D2COMMON_BASE		0x6FD50000
#define D2GFX_BASE			0x6FA80000
#define D2LAUNCH_BASE		0x6FA40000
#define D2MCPCLIENT_BASE	0x6FA20000
#define D2MULTI_BASE		0x6F9D0000
#define D2NET_BASE			0x00CD0000
#define D2WIN_BASE			0x6F8E0000
#define FOG_BASE			0x6FF50000
#define STORM_BASE			0x6FBF0000

#endif

#define D2PTRS_START	BNCLIENT_SendBNMessage

FUNCTION(BNCLIENT, SendBNMessage, VOID FASTCALL, (LPSTR Message), 0xC400)

FUNCTION(D2CLIENT, GetMonsterTxt, MonsterTxt * FASTCALL, (DWORD MonsterNumber), 0x1230)
FUNCTION(D2CLIENT, GetPlayerXOffset, DWORD STDCALL, (), 0x3F6C0)
FUNCTION(D2CLIENT, GetPlayerYOffset, DWORD STDCALL, (), 0x3F6D0)
FUNCTION(D2CLIENT, RecvCommand07, VOID FASTCALL, (LPBYTE Buffer), 0xAC3D0)
FUNCTION(D2CLIENT, RecvCommand08, VOID FASTCALL, (LPBYTE Buffer), 0xAC440)
FUNCTION(D2CLIENT, PrintGameString, VOID STDCALL, (WCHAR * Message, INT Color), 0x7D850)
FUNCTION(D2CLIENT, PrintPartyString, VOID STDCALL, (WCHAR * Message, INT Color), 0x7D610)
FUNCTION(D2CLIENT, PrintGameString2, VOID STDCALL, (LPSTR Message), 0x7F780)

FUNCTION(D2CLIENT, SetSelectedUnit_I, VOID FASTCALL, (LPUNITANY Unit), 0x51860)
FUNCTION(D2CLIENT, GetSelectedUnit, LPUNITANY STDCALL, (), 0x51A80)
FUNCTION(D2CLIENT, GetDifficulty, BYTE STDCALL, (), 0x41930)
FUNCTION(D2CLIENT, GetUnknownFlag, DWORD FASTCALL, (), 0x37A60)
FUNCTION(D2CLIENT, GetGameInfo, LPGAMESTRUCTINFO STDCALL, (), 0x108B0)
FUNCTION(D2CLIENT, GetAutomapSize, DWORD STDCALL, (), 0x5F080)
FUNCTION(D2CLIENT, NewAutomapCell, AutomapCell * FASTCALL, (), 0x5F6B0)
FUNCTION(D2CLIENT, AddAutomapCell, VOID FASTCALL, (AutomapCell *aCell, AutomapCell **node), 0x61320)
FUNCTION(D2CLIENT, RevealAutomapRoom, VOID STDCALL, (Room1 *pRoom1, DWORD dwClipFlag, AutomapLayer *aLayer), 0x62580)
FUNCTION(D2CLIENT, InitAutomapLayer_I, LPAUTOMAPLAYER FASTCALL, (DWORD nLayerNo), 0x62710)
FUNCTION(D2CLIENT, GetMonsterOwner, DWORD FASTCALL, (DWORD nMonsterId), 0x216A0)
FUNCTION(D2CLIENT, GetUiVar_I, DWORD FASTCALL, (DWORD dwVarNo), 0xBE400)
FUNCTION(D2CLIENT, SetUIState, DWORD FASTCALL, (DWORD varno, DWORD howset, DWORD unknown1), 0xC2794)
FUNCTION(D2CLIENT, GetItemNameString, VOID STDCALL, (LPUNITANY pItem, WCHAR *wItemName, INT nLen), 0x914F0)
FUNCTION(D2CLIENT, CalculateShake, VOID STDCALL, (DWORD *dwPosX, DWORD *dwPosY), 0x8AFD0)
FUNCTION(D2CLIENT, GetPlayerUnit, LPUNITANY  STDCALL, (), 0xA4D60)
FUNCTION(D2CLIENT, DrawRectFrame, VOID FASTCALL, (DWORD Rect), 0xBE4C0)
FUNCTION(D2CLIENT, ExitGame, VOID FASTCALL, (), 0x42850)
FUNCTION(D2CLIENT, Attack, VOID STDCALL, (LPATTACKSTRUCT Attack, BOOL AttackingUnit), 0x1A060)
FUNCTION(D2CLIENT, GetItemName, BOOL STDCALL, (LPUNITANY pItem, WCHAR * wBuffer, DWORD dwSize), 0x914F0)
FUNCTION(D2CLIENT, AcceptTrade, VOID FASTCALL, (), 0x59600)
FUNCTION(D2CLIENT, DrawEnteringLevelText, VOID STDCALL, (), 0xBF0D0)
FUNCTION(D2CLIENT, DrawManaOrb, VOID STDCALL, (), 0x27A90)
FUNCTION(D2CLIENT, DrawPartyName ,VOID STDCALL, (LPSTR pR, DWORD yPos, DWORD Col, DWORD UNK), 0x75780)
FUNCTION(D2CLIENT, CancelTrade, VOID FASTCALL, (), 0x8CB90)
FUNCTION(D2CLIENT, CreateAttack, VOID STDCALL, (LPUNITANY Unit, DWORD SkillID, DWORD SkillLevel, BOOL Unknown), 0xA2C90)
FUNCTION(D2CLIENT, ClearScreen, VOID FASTCALL, (), 0x492F0)
FUNCTION(D2CLIENT, GetQuestInfo, LPVOID STDCALL, (), 0x45A00)
FUNCTION(D2CLIENT, UnitTestSelect, DWORD STDCALL, (UnitAny* pUnit, DWORD _1, DWORD _2, DWORD _3), 0xA68E0)
FUNCTION(D2CLIENT, FindServerSideUnit, LPUNITANY FASTCALL, (DWORD dwId, DWORD dwType), 0xA5B40)
FUNCTION(D2CLIENT, FindClientSideUnit, LPUNITANY FASTCALL, (DWORD dwId, DWORD dwType), 0xA5B20)
FUNCTION(D2CLIENT, SetUIVar, DWORD FASTCALL, (DWORD varno, DWORD howset, DWORD unknown1), 0xC2790)
FUNCTION(D2CLIENT, ClickMap, VOID STDCALL, (DWORD MouseFlag, DWORD x, DWORD y, DWORD Type), 0x1BF20)
FUNCTION(D2CLIENT, GetCursorItem, UnitAny* FASTCALL, (), 0x16020)
FUNCTION(D2CLIENT, LeftClickItem, VOID STDCALL, (UnitAny* pPlayer, Inventory* pInventory, INT x, INT y, DWORD dwClickType, InventoryLayout* pLayout, DWORD Location), 0x96AA0)
FUNCTION(D2CLIENT, CloseNPCInteract, VOID FASTCALL, (), 0x48350)
FUNCTION(D2CLIENT, CloseInteract, VOID FASTCALL, (), 0x43870)
FUNCTION(D2CLIENT, ChatBoxHandler, DWORD STDCALL, (MSG* pMsg), 0x70C40)
FUNCTION(D2CLIENT, InitInventory, VOID FASTCALL, (), 0x908C0)
FUNCTION(D2CLIENT, FixShopActions, VOID FASTCALL, (), 0x47AB0)
FUNCTION(D2CLIENT, SubmitItem, VOID FASTCALL, (DWORD dwItemId), 0x45FB0)
FUNCTION(D2CLIENT, GetUnitHPPercent, DWORD FASTCALL, (DWORD dwUnitId), 0x21590)
FUNCTION(D2CLIENT, GetMercUnit, UnitAny* FASTCALL, (), 0x97CD0)
FUNCTION(D2CLIENT, ShopAction, VOID FASTCALL, (UnitAny* pItem, UnitAny* pNpc, UnitAny* pNpc2, DWORD dwSell, DWORD dwItemCost, DWORD dwMode, DWORD _2, DWORD _3), 0x47D60)
FUNCTION(D2CLIENT, GetCurrentINTeractingNPC, UnitAny* FASTCALL, (), 0x7C5C0)
FUNCTION(D2CLIENT, PerformGoldDialogAction, VOID FASTCALL, (), 0xBFDF0)
FUNCTION(D2CLIENT, LeaveParty, VOID FASTCALL, (), 0x9E5D0)
FUNCTION(D2CLIENT, Transmute, VOID FASTCALL, (), 0x595C0)
FUNCTION(D2CLIENT, CalcShake, VOID STDCALL, (DWORD * xpos, DWORD * ypos), 0x8AFD0)
FUNCTION(D2CLIENT, SocketProtectionPatchOriginal, VOID STDCALL, (LPUNITANY Unit, DWORD Argument), 0x23200)
FUNCTION(D2CLIENT, GetUnitX, INT FASTCALL, (LPUNITANY pUnit), 0x1630)
FUNCTION(D2CLIENT, GetUnitY, INT FASTCALL, (LPUNITANY pUnit), 0x1660)
FUNCTION(D2CLIENT, GetUnit, LPUNITANY FASTCALL, (DWORD dwId, DWORD dwType), 0x78D30)

VARIABLE(D2CLIENT, AutomapLayer, LPAUTOMAPLAYER, 0x11C1C4)
VARIABLE(D2CLIENT, AutomapLayerList, LPAUTOMAPLAYER, 0x11C1C0)
VARIABLE(D2CLIENT, Difficulty, BYTE, 0x11C390)
VARIABLE(D2CLIENT, ExpCharFlag, DWORD, 0x119854)
VARIABLE(D2CLIENT, ServerIp, CHAR, 0xF4320)
VARIABLE(D2CLIENT, AutomapOn, DWORD, 0xFADA8)
VARIABLE(D2CLIENT, PtAutomap, POINT, 0x11C23C)
VARIABLE(D2CLIENT, InSocketablePatch, LPUNITANY, 0x11BC38)
VARIABLE(D2CLIENT, ChatMessage, WCHAR, 0x11EC80)
VARIABLE(D2CLIENT, ExitAppFlag, DWORD, 0xF8C9C)
VARIABLE(D2CLIENT, PlayerUnit, LPUNITANY, 0x11BBFC)
VARIABLE(D2CLIENT, PlayerUnitList, LPROSTERUNIT, 0x11BC14)
VARIABLE(D2CLIENT, pUnitList, LPUNITANY, 0x10A608)
VARIABLE(D2CLIENT, FPS, DWORD, 0x11C2AC)
VARIABLE(D2CLIENT, Skip, DWORD, 0x119810)
VARIABLE(D2CLIENT, Ping, DWORD, 0x119804)
VARIABLE(D2CLIENT, Divisor, INT, 0xF16B0)
VARIABLE(D2CLIENT, Offset, POINT, 0x11C1F8)
VARIABLE(D2CLIENT, PlayerAct, Act *, 0x11C3B8)
VARIABLE(D2CLIENT, TextLength, INT, 0x11C028)
VARIABLE(D2CLIENT, MouseX, DWORD, 0x11B828)
VARIABLE(D2CLIENT, MouseY, DWORD, 0x11B824)
VARIABLE(D2CLIENT, MouseOffsetX, INT, 0x119960)
VARIABLE(D2CLIENT, MouseOffsetY, INT, 0x11995C)
VARIABLE(D2CLIENT, MouseOffsetZ, INT, 0x11C418)
VARIABLE(D2CLIENT, ScreenSizeX, DWORD, 0xDBC48)
VARIABLE(D2CLIENT, ScreenSizeY, DWORD, 0xDBC4C)
VARIABLE(D2CLIENT, ShakeX, INT, 0x11BF00)
VARIABLE(D2CLIENT, ShakeY, INT, 0x10B9DC)
VARIABLE(D2CLIENT, MonsterLifeNamePatch1, UnitAny, 0xE0EA8)
VARIABLE(D2CLIENT, MonsterLifeNamePatch2, UnitAny, 0xE0EAF)

ASSEMBLER(D2CLIENT, AssignPlayer_I, 0xA7630)
ASSEMBLER(D2CLIENT, Attack_I, 0xDBC4C)
ASSEMBLER(D2CLIENT, Attack_II, 0x11B824)
ASSEMBLER(D2CLIENT, GetUnitFromId_I, 0x10A608)
ASSEMBLER(D2CLIENT, GetUnitFromId_II, 0xA4E20)
ASSEMBLER(D2CLIENT, GetUnitName_I, 0xA5D90)
ASSEMBLER(D2CLIENT, InputCall_I, 0x147A0)
ASSEMBLER(D2CLIENT, LoadAct_1, 0x62AA0)
ASSEMBLER(D2CLIENT, LoadAct_2, 0x62760)
ASSEMBLER(D2CLIENT, LoadUiImage_I, 0x2B420)
ASSEMBLER(D2CLIENT, OverrideShrinePatchOriginal, 0x1155B8)
ASSEMBLER(D2CLIENT, TestPvPFlag_I, 0x4FD90)

FUNCTION(D2CMP, InitCellFile, VOID STDCALL, (LPVOID File, LPCELLFILE * Out, LPSTR SourceFile, DWORD Line, DWORD FileVersion, LPSTR Filename), -10006)
FUNCTION(D2CMP, DeleteCellFile, VOID STDCALL, (LPCELLFILE File), -10065)

FUNCTION(D2COMMON, AbsScreenToMap, VOID STDCALL, (LONG * ptMouseX, LONG * ptMouseY), -10474)
FUNCTION(D2COMMON, AddRoomData, VOID STDCALL, (Act * ptAct, INT LevelId, INT Xpos, INT Ypos, Room1 * pRoom), -10401)
FUNCTION(D2COMMON, AddUnitStat, LPUNITANY STDCALL, (DWORD Stat, DWORD Amount, DWORD Unknown), -10551)
FUNCTION(D2COMMON, RemoveRoomData, VOID STDCALL, (Act * ptAct, INT LevelId, INT Xpos, INT Ypos, Room1 * pRoom), -11099)
FUNCTION(D2COMMON, GetItemText, LPITEMTXT STDCALL, (DWORD itemno), -10695)
FUNCTION(D2COMMON, GetLayer, AutomapLayer2* FASTCALL, (DWORD dwLevelNo), -10749)
FUNCTION(D2COMMON, GetLevel, Level * FASTCALL, (ActMisc *pMisc, DWORD dwLevelNo), -10207)
FUNCTION(D2COMMON, GetLevelTxt, LPLEVELTXT STDCALL, (DWORD LevelNumber), -10014)
FUNCTION(D2COMMON, InitLevel, VOID STDCALL, (Level *pLevel), -10322)
FUNCTION(D2COMMON, GetCursorItem, LPUNITANY STDCALL, (LPINVENTORY ptInventory), -11017)
FUNCTION(D2COMMON, GetItemFromInventory, DWORD STDCALL, (LPINVENTORY Inv), -10460)
FUNCTION(D2COMMON, GetUnitFromItem, LPUNITANY STDCALL, (DWORD Argument), -11147)
FUNCTION(D2COMMON, GetNextItemFromInventory, DWORD STDCALL, (DWORD pItem), -10464)
FUNCTION(D2COMMON, GetObjectTxt, LPOBJECTTXT STDCALL, (DWORD objno), -10688)
FUNCTION(D2COMMON, GetSuperUniqueTxt, LPSUPERUNIQUETXT STDCALL, (DWORD monno), -10038)
FUNCTION(D2COMMON, GetUnitStat, DWORD STDCALL, (LPUNITANY Unit, DWORD Stat, DWORD Stat2), -10973)
FUNCTION(D2COMMON, GetUnitState, INT STDCALL, (LPUNITANY Unit, DWORD State), -10494)
FUNCTION(D2COMMON, GetFunUnk_5, DWORD STDCALL, (DWORD nLevelNo), -10698)
FUNCTION(D2COMMON, LoadAct, LPACT STDCALL, (DWORD ActNumber, DWORD MapId, DWORD Unk, DWORD Unk_2, DWORD Unk_3, DWORD Unk_4, DWORD TownLevelId, DWORD Func_1, DWORD Func_2), 0x3CB30)
FUNCTION(D2COMMON, UnloadAct, VOID STDCALL, (LPACT pAct), -10868)
FUNCTION(D2COMMON, MapToAbsScreen, VOID STDCALL, (LONG * X, LONG * Y), -11087)
FUNCTION(D2COMMON, TestFunUnk_6, DWORD STDCALL, (LPUNITANY Unit1, LPUNITANY Unit2, DWORD arg3), -10233)
FUNCTION(D2COMMON, CheckUnitCollision, DWORD STDCALL, (LPUNITANY pUnitA, LPUNITANY pUnitB, DWORD dwBitMask), -10839)
FUNCTION(D2COMMON, CheckCollision, DWORD STDCALL, (LPROOM1 pRoom, DWORD X, DWORD Y, DWORD dwBitMask), -10482)
FUNCTION(D2COMMON, GetRoomFromUnit, LPROOM1 STDCALL, (LPUNITANY ptUnit), -10331)
FUNCTION(D2COMMON, GetTargetUnitType, LPPATH STDCALL, (LPPATH pPath), -10392)
FUNCTION(D2COMMON, GetTreasureClasses, LPTREASURECLASS STDCALL, (DWORD tcno, DWORD lvlno), -10634)

FUNCTION(D2GFX, DrawAutomapCell, VOID STDCALL, (LPCELLCONTEXT Context, DWORD X, DWORD Y, RECT * Clip, DWORD Bright), -10079)
FUNCTION(D2GFX, DrawLine, VOID STDCALL, (INT x1, INT y1, INT x2, INT y2, DWORD color, DWORD unk), -10010)
FUNCTION(D2GFX, DrawRectangle, VOID STDCALL, (INT x1, INT y1, INT x2, INT y2, DWORD color, DWORD trans), -10014)
FUNCTION(D2GFX, GetHwnd, HWND STDCALL, (), 0x7FB0)
FUNCTION(D2GFX, GetScreenSize, DWORD STDCALL, (), -10031)
FUNCTION(D2GFX, GetScreenSize2, DWORD STDCALL, (), -10036)

FUNCTION(D2MCPCLIENT, ParseGameListPacket, VOID FASTCALL, (LPBYTE Packet), 0x63E0)

FUNCTION(D2MULTI, PrintChannelText, VOID STDCALL, (CHAR * szText, DWORD dwColor), 0xFB40)
FUNCTION(D2MULTI, DoChat, VOID FASTCALL, (), 0xCB30)

VARIABLE(D2MULTI, ChatBoxMsg, LPSTR, 0x38F18)
VARIABLE(D2MULTI, EditboxPreferences, LPCONTROLPREFERENCES, 0x19C60)
VARIABLE(D2MULTI, GameListControl, LPCONTROL, 0x39CC0)

FUNCTION(D2NET, SendPacket, VOID STDCALL, (DWORD aLen, DWORD arg1, BYTE* aPacket), -10024)
FUNCTION(D2NET, ReceivePacket, VOID STDCALL, (BYTE *aPacket, DWORD aLen), 0x6BD0)
FUNCTION(D2NET, ReceivePacket_I, VOID STDCALL, (BYTE *aPacket, DWORD aLen), -10033)

VARIABLE(D2NET, CriticalPacketSection, CRITICAL_SECTION, 0xB400)

FUNCTION(D2WIN, DrawText, VOID FASTCALL, (CONST WCHAR * text, INT x, INT y, INT color, DWORD unk), -10150)
FUNCTION(D2WIN, SetControlText, LPVOID FASTCALL, (LPCONTROL box, WCHAR * txt), -10042)
FUNCTION(D2WIN, GetTextLength, DWORD FASTCALL, (WCHAR * szwText), -10028)
FUNCTION(D2WIN, GetTextWidthFileNo, DWORD FASTCALL, (WCHAR * wStr, DWORD* dwWidth, DWORD* dwFileNo), -10177)
FUNCTION(D2WIN, CreateEditBox, LPCONTROL FASTCALL, (DWORD xPos, DWORD yPos, DWORD SizeX, DWORD SizeY, DWORD LeftOffset, DWORD TopOffset, LPCELLFILE CellFile, BOOL (STDCALL * OnAccept)(LPCONTROL), BOOL (STDCALL * OnClick)(LPCONTROL), DWORD IsCloaked, LPCONTROLPREFERENCES Preferences), -10057)
FUNCTION(D2WIN, DestroyControl, VOID STDCALL, (LPCONTROL pControl), -10050)
FUNCTION(D2WIN, DestroyEditBox, VOID FASTCALL, (LPCONTROL pControl), -10048)
FUNCTION(D2WIN, GetEditBoxText, WCHAR * FASTCALL, (LPCONTROL box), 0x136A0)
FUNCTION(D2WIN, AddEditBoxChar, DWORD FASTCALL, (LPCONTROL box, BYTE keycode), 0x15450)
FUNCTION(D2WIN, SetEditBoxCallback, VOID FASTCALL, (LPCONTROL pControl, BOOL (STDCALL * FunCallBack)(LPCONTROL pControl, DWORD dwInputType, LPSTR pChar)), -10170)
FUNCTION(D2WIN, SetEditBoxProc, VOID FASTCALL, (LPCONTROL box, BOOL (STDCALL * FunCallBack)(LPCONTROL, DWORD, DWORD)), 0x13970)
FUNCTION(D2WIN, SetEditBoxText, LPVOID FASTCALL, (LPCONTROL box, WCHAR * txt), 0x14DF0)
FUNCTION(D2WIN, SelectEditBoxText, VOID FASTCALL, (LPCONTROL box, WCHAR * txt), 0x7708)
FUNCTION(D2WIN, SetTextSize, DWORD FASTCALL, (DWORD dwSize), -10184)
FUNCTION(D2WIN, TakeScreenshot, VOID FASTCALL, (), 0x17EB0)

VARIABLE(D2WIN, FirstControl, LPCONTROL, 0x214A0)
VARIABLE(D2WIN, FocusedControl, LPCONTROL, 0x214B0)

ASSEMBLER(D2WIN, WindowProc_I, 0x214C0)

#define D2PTRS_END	D2WIN_WindowProc_I

#undef FUNCTION
#undef VARIABLE
#undef ASSEMBLER

#define AutoMapLayer						(*p_D2CLIENT_AutomapLayer)
#define AutoMapLayerList					(*p_D2CLIENT_AutomapLayerList)
#define FPS									(*p_D2CLIENT_FPS)
#define GetMonsterOwner(ID)					(D2CLIENT_GetMonsterOwner(ID))
#define GetInventoryID(Unit, ID, Unknown)	(GetInventoryIDSTUB(Unit, ID, Unknown))
#define GetUIVar(UI)						(GetUIVarSTUB(UI))
#define GetUnit(ID, Type)					(GetUnitSTUB(ID, Type))
#define GetUnitName(X)						(GetUnitNameSTUB((DWORD)X))
#define GetUnitStat(Unit, Stat)				(D2COMMON_GetUnitStat(Unit, Stat, 0))
#define GetUnitState(Unit, State)			(D2COMMON_GetUnitState(Unit, State))
#define Me									(*p_D2CLIENT_PlayerUnit)
#define MouseX								(*p_D2CLIENT_MouseX)
#define MouseY								(*p_D2CLIENT_MouseY)
#define Ping								(*p_D2CLIENT_Ping)
#define Skip								(*p_D2CLIENT_Skip)
#define TestPvPFlag(ID1, ID2, Flag)			(TestPvPFlagSTUB(ID1, ID2, Flag))