#define CopyAndPasteBugFix	INST_JMP
#define FloorsInside		INST_NOP
#define LeftClickAllSkills	0xEB
#define ShiftClickFarcast	0x01
#define ShrineDistance		INST_NOP
#define WallsInside			INST_NOP

PATCH Patches[] =
{
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x61D83),	(DWORD)AddShrineSTUB,					6,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0xA302B),	(DWORD)AfterAttackSTUB,					10,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x3CB20),	(DWORD)AttackLoop,						6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x604EA),	(DWORD)AutomapCells,					5,	INGAME},
	{PatchJmp,		DLLOFFSET(D2CLIENT,		0xC3DB5),	(DWORD)DrawSTUB,						5,	INGAME},
	{PatchJmp,		DLLOFFSET(D2CLIENT,		0x626C9),	(DWORD)DrawAutomapSTUB,					5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0xC3AA1),	(DWORD)DrawEnteringLevelTextSTUB,		5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x2929E),	(DWORD)DrawManaOrbSTUB,					5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x45153),	(DWORD)EndSTUB,							5,	INGAME},
	{PatchFill,		DLLOFFSET(D2CLIENT,		0x625C4),	(DWORD)FloorsInside,					2,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0xA9A27),	(DWORD)FullLightRadiusSTUB,				5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0xA3030),	(DWORD)GameAfterAttack,					5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x442A2),	(DWORD)GameShake,						5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x1BF94),	(DWORD)GetSelectedUnit,					5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x9A695),	(DWORD)GetViewingUnit,					5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0xBCBA3),	(DWORD)GetViewingUnit,					5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0xBCEA6),	(DWORD)GetViewingUnit,					5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0xBD743),	(DWORD)GetViewingUnit,					5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0xBB983),	(DWORD)InfraVisionSTUB,					7,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x70C6C),	(DWORD)InputLineSTUB1,					5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x7037B),	(DWORD)InputLineSTUB2,					5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x70B75),	(DWORD)InputSTUB,						5,	INGAME},
	{PatchBytes,	DLLOFFSET(D2CLIENT,		0x3F8DF),	(DWORD)INST_NOP,						2,	INGAME},
	{PatchBytes,	DLLOFFSET(D2CLIENT,		0x1A073),	(DWORD)INST_NOP,						6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x55C1D),	(DWORD)ItemBasicStatSTUB,				5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x92366),	(DWORD)ItemNameSTUB,					6,	INGAME},
	{PatchBytes,	DLLOFFSET(D2CLIENT,		0x3E8E4),	(DWORD)LeftClickAllSkills,				1,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x61E70),	(DWORD)LoadAutomapLayerFromFileSTUB,	6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x44230),	(DWORD)LoopSTUB,						7,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x7D8A8),	(DWORD)MessageLogSTUB1,					5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x7D61F),	(DWORD)MessageLogSTUB2,					5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x20FBE),	(DWORD)MonsterDeathSTUB,				5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x1FE3B),	(DWORD)MonsterDescCommaSTUB1,			5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x1FF25),	(DWORD)MonsterDescCommaSTUB2,			5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0xC0C01),	(DWORD)MonsterDescCommaSTUB3,			6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x38BB5),	(DWORD)OnGameKeyDownSTUB,				7,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0xACE61),	(DWORD)OnGamePacketReceivedSTUB,		5,	INGAME},
	{PatchJmp,		DLLOFFSET(D2CLIENT,		0xD252),	(DWORD)OnGamePacketSentSTUB,			6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x1A060),	(DWORD)OnUseSkillSTUB,					5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x1BF25),	(DWORD)OutTownSelectSTUB1,				6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0xA6941),	(DWORD)OutTownSelectSTUB2,				6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0xA69EE),	(DWORD)OutTownSelectSTUB3,				6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x61354),	(DWORD)OverrideShrineSTUB,				7,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0xC5A24),	(DWORD)PassingActBugFixSTUB,			9,	INGAME},
	//{PatchJmp,		DLLOFFSET(D2CLIENT,		0xADF37),	(DWORD)PlayerAssignmentSTUB,			5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x6175D),	(DWORD)PlayerBlobSTUB,					6,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x61140),	(DWORD)SaveAutomapLayerToFileSTUB,		5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x8B096),	(DWORD)ShakeSTUB,						6,	INGAME},
	{PatchBytes,	DLLOFFSET(D2CLIENT,		0x1B7A7),	(DWORD)ShiftClickFarcast,				1,	INGAME},
	{PatchFill,		DLLOFFSET(D2CLIENT,		0x61D31),	(DWORD)ShrineDistance,					6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x99174),	(DWORD)SocketProtectionSTUB1,			6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x96FAB),	(DWORD)SocketProtectionSTUB2,			6,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x93450),	(DWORD)SocketViewtableSTUB1,			5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x933E2),	(DWORD)SocketViewtableSTUB2,			5,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x953E2),	(DWORD)ViewInventorySTUB1,				6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x94AB4),	(DWORD)ViewInventorySTUB2,				6,	INGAME},
	{PatchCall,		DLLOFFSET(D2CLIENT,		0x93A6F),	(DWORD)ViewInventorySTUB3,				5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x99120),	(DWORD)ViewInventorySTUB4,				5,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0x2FE63),	(DWORD)ViewStatSTUB1,				6,	INGAME},
	//{PatchCall,		DLLOFFSET(D2CLIENT,		0xBC524),	(DWORD)ViewStatSTUB2,				6,	INGAME},
	{PatchFill,		DLLOFFSET(D2CLIENT,		0x6260A),	(DWORD)WallsInside,						2,	INGAME},

	//{PatchJmp,		DLLOFFSET(D2COMMON,		0x325B1),	(DWORD)FrameRemainSTUB,					5,	INGAME},
	{PatchJmp,		DLLOFFSET(D2COMMON,		0x6CCB6),	(DWORD)WeatherSTUB,						5,	INGAME},

	{PatchCall,		DLLOFFSET(D2MCPCLIENT,	0x69D7),	(DWORD)OnMCPPacketReceivedSTUB,			5,	OUTGAME},

	{PatchCall,		DLLOFFSET(D2MULTI,		0x149EF),	(DWORD)CreateGameBoxSTUB,				5,	OUTGAME},
	{PatchCall,		DLLOFFSET(D2MULTI,		0x11DC3),	(DWORD)DestroyGameList,					5,	OUTGAME},
	{PatchCall,		DLLOFFSET(D2MULTI,		0x14A0B),	(DWORD)NextGameName,					5,	OUTGAME},
	{PatchCall,		DLLOFFSET(D2MULTI,		0x14D29),	(DWORD)NextGameName,					5,	OUTGAME},
	{PatchCall,		DLLOFFSET(D2MULTI,		0x14A46),	(DWORD)NextGamePassword,				5,	OUTGAME},
	{PatchCall,		DLLOFFSET(D2MULTI,		0x14D64),	(DWORD)NextGamePassword,				5,	OUTGAME},
	{PatchCall,		DLLOFFSET(D2MULTI,		0xDF4E),	(DWORD)RefreshGameListSTUB,				5,	OUTGAME},

	//{PatchFill,		DLLOFFSET(D2WIN,		0x9E1A),	(DWORD)CopyAndPasteBugFix,				1,	INGAME},
	//{PatchCall,		DLLOFFSET(D2WIN,		0x12C68),	(DWORD)LifeBarSTUB,						6,	INGAME},
	{PatchCall,		DLLOFFSET(D2WIN,		0x118F0),	(DWORD)MonsterLifeBarNameSTUB,			6,	INGAME},
	//{PatchCall,		DLLOFFSET(D2WIN,		0x17740),	(DWORD)WindowProcSTUB,					5,	INGAME},
	{PatchCall,		DLLOFFSET(D2WIN,		0x18911),	(DWORD)WinDrawSTUB,						5,	OUTGAME}
};